import type { RouteRecordRaw } from "vue-router"
const routes:RouteRecordRaw[] =[
    {
        path:"/",
        name:"Home",
        component:()=>import("@/layouts/DefaultLayout.vue"),
        redirect:"/dashboard",
        children:[
            {
                path:"/dashboard",
                name:"dashboard",
                component:()=>import("@/pages/dashboard/Dashboard.vue")
            },
            {
                path:"/chargingstation/monitor",
                name:"monitor",
                component:()=>import("@/pages/chargingstation/Monitor.vue")
            },
            {
                path:"/chargingstation/revenue",
                name:"revenue",
                component:()=>import("@/pages/chargingstation/Revenue.vue")
            },
            {
                path:"/chargingstation/fault",
                name:"fault",
                component:()=>import("@/pages/chargingstation/Fault.vue")
            },
            {
                path:"/map",
                name:"map",
                component:()=>import("@/pages/map/Map.vue")
            },
            {
                path:"/operations/orders",
                name:"orders",
                component:()=>import("@/pages/operationes/Orders.vue"),
                meta:{
                    keepAlive:true
                }
            },
            {
                path:"/operations/detail",
                name:"detail",
                component:()=>import("@/pages/operationes/Details.vue")
            },
            {
                path:"/operations/total",
                name:"total",
                component:()=>import("@/pages/operationes/Total.vue")
            },
            {
                path:"/alarm",
                name:"alarm",
                component:()=>import("@/pages/alarm/Alarm.vue")
            },
            {
                path:"/equipment",
                name:"equipment",
                component:()=>import("@/pages/equipment/Equipment.vue")
            },
            {
                path:"/document",
                name:"document",
                component:()=>import("@/pages/document/Document.vue"),
                meta:{
                    needAuth:["admin","manager"]
                }
            },
            {
                path:"/system",
                name:"system",
                component:()=>import("@/pages/system/System.vue"),
                meta:{
                    needAuth:["admin"]
                }
            },
            {
                path:"/personal",
                name:"personal",
                component:()=>import("@/pages/personal/Personal.vue")
            },
        ]
    },
    {
        path:"/login",
        name:"login",
        component:()=>import("@/pages/Login/Login.vue")
    },
    {
        path:"/:pathMatch(.*)*",
        name:"NotFound",
        component:()=>import("@/pages/NotFound/NotFound.vue")
    },
]

export default routes